// Generated by CodiumAI
//import { Notify } from "quasar";
import { Notify } from "quasar";

describe("useNotify", () => {
  // Test that a notification of type 'positive' with a message is created
  it("should create a notification of type positive with a message", () => {
    const mockNotify = jest.fn();
    jest.mock("quasar", () => ({
      Notify: {
        create: mockNotify,
      },
    }));
    const useNotify = require("../../../src/composables/useNotify").default;
    const notify = useNotify();
    notify.notifySuccess("Test message");

    expect(mockNotify).toHaveBeenCalledWith({
      type: "positive",
      message: "Test message",
      timeout: 2000,
      icon: "",
      actions: [{ label: "Ok", color: "white" }],
    });
  });

  it("should create a notification of type negative with a message", () => {
    const mockNotify = jest.fn();
    jest.mock("quasar", () => ({
      Notify: {
        create: mockNotify,
      },
    }));
    const useNotify = require("../../../src/composables/useNotify").default;
    const notify = useNotify();
    notify.notifyError("Something went wrong");
    expect(mockNotify).toHaveBeenCalledWith({
      type: "negative",
      message: "Something went wrong",
      timeout: 2000,
      icon: "",
      actions: [{ label: "Ok", color: "white" }],
    });
  });
});
